TebLocalPlannerROS:

 odom_topic: odom #need to be modified /map
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 max_samples: 500
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: True
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 0
    
 # Robot
         
 max_vel_x: 4.0 #20km/h to 5.55m/s, for safe, i set 2
 max_vel_x_backwards: 2.0 #20km/h to 5.55m/s, for safe, i set 2
 max_vel_y: 0.0
 max_vel_theta: 0.3 # need to be modified, 27degree to 0.471radian/sec
 acc_lim_x: 6.0 #need to be modified
 acc_lim_theta: 0.5 # need to be modified


 min_turning_radius: 2.04 #2.04 Min turning radius of the carlike robot (compute value using a model or adjust with rqt_reconfigure manually) need to be modified. wheelbase / tan(max steer)
 wheelbase: -1.04   
 cmd_angle_instead_rotvel: True

 footprint_model:
   type: "line"
   
   line_start: [0.0, 0.0] # for type "line"
   line_end: [1.04, 0.0] # for type "line"
   
 # GoalTolerance
    
 xy_goal_tolerance: 0.5
 yaw_goal_tolerance: 0.2
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.693 # sqrt(69^2+69^2) 0.693
 inflation_dist: 0.8 #0.8
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.5
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 2.0
 weight_max_vel_theta: 1.0
 weight_acc_lim_x: 1.0
 weight_acc_lim_theta: 1.0
 weight_kinematics_nh: 1000.0
 weight_kinematics_forward_drive: 1.0  #1
 weight_kinematics_turning_radius: 1.0
 weight_optimaltime: 1.0
 weight_inflation: 0.2
 weight_obstacle: 50.0
 weight_dynamic_obstacle: 10 # not in use yet
 weight_adapt_factor: 2.0
 weight_viapoint: 1.0
 weight_adapt_factor: 2.0

 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 selection_cost_hysteresis: 1.0
 selection_obst_cost_scale: 1.0
 selection_alternative_time_cost: False
 
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False

# Recovery
 
 shrink_horizon_backup: True
 shrink_horizon_min_duration: 10
 oscillation_recovery: True
 oscillation_v_eps: 0.1
 oscillation_omega_eps: 0.1
 oscillation_recovery_min_duration: 10
 oscillation_filter_duration: 10
