TebLocalPlannerROS:

 odom_topic: odom #need to be modified /map
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 max_samples: 500
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: True
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 0
    
 # Robot
         
 max_vel_x: 2.5 #20km/h to 5.55m/s, for safe, i set 2
 max_vel_x_backwards: 2.0 #20km/h to 5.55m/s, for safe, i set 2
 max_vel_y: 0.0
 max_vel_theta: 0.6 # need to be modified, 27degree to 0.471radian/sec
 acc_lim_x: 3.0 #need to be modified 6
 acc_lim_theta: 0.9 # need to be modified


 min_turning_radius: 2.04 #2.04 Min turning radius of the carlike robot (compute value using a model or adjust with rqt_reconfigure manually) need to be modified. wheelbase / tan(max steer)
 wheelbase: 1.04   
 cmd_angle_instead_rotvel: True

 footprint_model:
   type: "two_circles"
   
#   line_start: [-0.52, 0.0] # for type "line"
#   line_end: [0.52, 0.0] # for type "line"
   front_offset: 1.0 # for type "two_circles"
   front_radius: 0.49 # for type "two_circles"
   rear_offset: 0.01 # for type "two_circles"
   rear_radius: 0.49 # for type "two_circles"
 # GoalTolerance
    
 xy_goal_tolerance: 0.47
 yaw_goal_tolerance: 0.15
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.3 # sqrt(69^2+69^2) 0.693
 inflation_dist: 0.35 #0.8
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.5
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5


 weight_kinematics_nh: 1000.0
 weight_kinematics_forward_drive: 1000.0  #1


 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 selection_cost_hysteresis: 1.0
 selection_obst_cost_scale: 1.0
 selection_alternative_time_cost: False
 
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False

# Recovery
 
 shrink_horizon_backup: True
 shrink_horizon_min_duration: 10
 oscillation_recovery: True
 oscillation_v_eps: 0.1
 oscillation_omega_eps: 0.1
 oscillation_recovery_min_duration: 10
 oscillation_filter_duration: 10

